"""Seeds the exercise library.

100 real exercises spanning all 7 categories the library was specified to
support (chest, back, shoulders, legs, arms, core, cardio). Idempotent: if
the table already has rows, `seed_exercises` does nothing — safe to call on
every startup (see `app/main.py`), not just the first one.

Each row is validated through `ExerciseCreate` before insertion (catches a
typo'd enum value or an out-of-range number the same way the future
create-exercise endpoint would reject one), then persisted in a single
transaction via `exercise_repository.bulk_create` rather than 100 individual
service calls.
"""

from sqlalchemy.orm import Session

from app.repositories import exercise_repository
from app.schemas.exercise import ExerciseCreate

_EXERCISES: list[dict] = [
    # ---------------------------------------------------------------- Chest
    dict(
        name="Barbell Bench Press",
        muscle_group="chest",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=4,
        default_reps="6-8",
        rest_seconds=90,
        calories_per_set=8.0,
        is_compound=True,
        instructions="Lie on a flat bench, grip the bar slightly wider than shoulder-width, lower it under control to mid-chest, then press up until your arms are fully extended.",
    ),
    dict(
        name="Incline Barbell Bench Press",
        muscle_group="chest",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=4,
        default_reps="6-10",
        rest_seconds=90,
        calories_per_set=7.5,
        is_compound=True,
        instructions="On a bench set to a 30-45 degree incline, lower the bar to your upper chest, then press it back up over your shoulders.",
    ),
    dict(
        name="Decline Barbell Bench Press",
        muscle_group="chest",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="8-10",
        rest_seconds=90,
        calories_per_set=7.5,
        is_compound=True,
        instructions="On a decline bench with your feet secured, lower the bar to your lower chest and press back up to full extension.",
    ),
    dict(
        name="Dumbbell Bench Press",
        muscle_group="chest",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=4,
        default_reps="8-12",
        rest_seconds=75,
        calories_per_set=7.0,
        is_compound=True,
        instructions="Lying on a flat bench with a dumbbell in each hand, press both dumbbells straight up over your chest, then lower with control until your upper arms are level with your torso.",
    ),
    dict(
        name="Incline Dumbbell Press",
        muscle_group="chest",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=4,
        default_reps="8-12",
        rest_seconds=75,
        calories_per_set=6.5,
        is_compound=True,
        instructions="On an incline bench, press both dumbbells up and slightly inward over your upper chest, then lower under control.",
    ),
    dict(
        name="Dumbbell Flyes",
        muscle_group="chest",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-15",
        rest_seconds=60,
        calories_per_set=5.0,
        is_compound=False,
        instructions="Lying on a flat bench with a slight bend in your elbows, lower the dumbbells out to your sides in an arc, then bring them back together above your chest.",
    ),
    dict(
        name="Push-Up",
        muscle_group="chest",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-20",
        rest_seconds=60,
        calories_per_set=5.0,
        is_compound=True,
        instructions="Hands slightly wider than shoulder-width, body in a straight line from head to heels, lower your chest to the floor and press back up.",
    ),
    dict(
        name="Wide-Grip Push-Up",
        muscle_group="chest",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-15",
        rest_seconds=60,
        calories_per_set=5.0,
        is_compound=True,
        instructions="Set your hands wider than shoulder-width to emphasize the chest, then lower and press as in a standard push-up.",
    ),
    dict(
        name="Diamond Push-Up",
        muscle_group="chest",
        equipment="bodyweight",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="8-12",
        rest_seconds=60,
        calories_per_set=5.5,
        is_compound=True,
        instructions="Form a diamond with your thumbs and index fingers under your chest, then lower and press, keeping elbows close to your body.",
    ),
    dict(
        name="Cable Chest Fly",
        muscle_group="chest",
        equipment="cable",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=60,
        calories_per_set=5.0,
        is_compound=False,
        instructions="Standing between two cable stacks set to chest height, bring both handles together in front of your chest in a wide arc, keeping a slight elbow bend.",
    ),
    dict(
        name="Pec Deck Machine",
        muscle_group="chest",
        equipment="machine",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=60,
        calories_per_set=4.5,
        is_compound=False,
        instructions="Seated with your back against the pad, bring both arm pads together in front of your chest, then return slowly to the start position.",
    ),
    dict(
        name="Chest Dip",
        muscle_group="chest",
        equipment="bodyweight",
        difficulty="advanced",
        exercise_type="strength",
        default_sets=3,
        default_reps="8-12",
        rest_seconds=90,
        calories_per_set=7.0,
        is_compound=True,
        instructions="On parallel bars, lean forward slightly and lower your body until your shoulders are below your elbows, then press back up.",
    ),
    dict(
        name="Machine Chest Press",
        muscle_group="chest",
        equipment="machine",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=75,
        calories_per_set=6.0,
        is_compound=True,
        instructions="Seated with your back flat against the pad, press both handles forward until your arms are extended, then return under control.",
    ),
    dict(
        name="Svend Press",
        muscle_group="chest",
        equipment="dumbbells",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Press two light plates together at chest height with both palms, then extend your arms straight out and pull back in, keeping constant pressure.",
    ),
    # ----------------------------------------------------------------- Back
    dict(
        name="Deadlift",
        muscle_group="back",
        equipment="barbell",
        difficulty="advanced",
        exercise_type="strength",
        default_sets=4,
        default_reps="5",
        rest_seconds=120,
        calories_per_set=10.0,
        is_compound=True,
        instructions="Feet hip-width under the bar, grip just outside your shins, flat back, drive through your heels to stand up tall, then lower the bar back down under control.",
    ),
    dict(
        name="Pull-Up",
        muscle_group="back",
        equipment="pull_up_bar",
        difficulty="advanced",
        exercise_type="strength",
        default_sets=4,
        default_reps="6-10",
        rest_seconds=90,
        calories_per_set=8.0,
        is_compound=True,
        instructions="Hang from the bar with an overhand grip slightly wider than shoulders, pull your chin above the bar, then lower with control to a full hang.",
    ),
    dict(
        name="Lat Pulldown",
        muscle_group="back",
        equipment="cable",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=4,
        default_reps="10-12",
        rest_seconds=75,
        calories_per_set=6.5,
        is_compound=True,
        instructions="Grip the bar wider than shoulder-width, pull it down to your upper chest while squeezing your shoulder blades together, then return under control.",
    ),
    dict(
        name="Bent-Over Barbell Row",
        muscle_group="back",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=4,
        default_reps="8-10",
        rest_seconds=90,
        calories_per_set=7.5,
        is_compound=True,
        instructions="Hinge at the hips with a flat back, pull the bar up to your lower ribs, then lower it back down without rounding your spine.",
    ),
    dict(
        name="Seated Cable Row",
        muscle_group="back",
        equipment="cable",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=75,
        calories_per_set=6.0,
        is_compound=True,
        instructions="Sitting upright with knees slightly bent, pull the handle to your torso while keeping your back straight, then extend your arms back out.",
    ),
    dict(
        name="One-Arm Dumbbell Row",
        muscle_group="back",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=60,
        calories_per_set=6.0,
        is_compound=True,
        instructions="With one knee and hand on a bench, pull the dumbbell up to your hip with the other arm, keeping your back flat, then lower with control.",
    ),
    dict(
        name="T-Bar Row",
        muscle_group="back",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=4,
        default_reps="8-10",
        rest_seconds=90,
        calories_per_set=7.5,
        is_compound=True,
        instructions="Straddling the bar with a flat back, pull the handles up to your chest, squeezing your shoulder blades, then lower under control.",
    ),
    dict(
        name="Face Pull",
        muscle_group="back",
        equipment="cable",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="15-20",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="With the cable at face height, pull the rope towards your face, flaring your elbows out and squeezing your rear shoulders at the end.",
    ),
    dict(
        name="Chin-Up",
        muscle_group="back",
        equipment="pull_up_bar",
        difficulty="advanced",
        exercise_type="strength",
        default_sets=4,
        default_reps="6-10",
        rest_seconds=90,
        calories_per_set=8.0,
        is_compound=True,
        instructions="Hang from the bar with an underhand, shoulder-width grip, pull your chin above the bar, then lower with control.",
    ),
    dict(
        name="Romanian Deadlift",
        muscle_group="back",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="8-10",
        rest_seconds=90,
        calories_per_set=7.0,
        is_compound=True,
        instructions="With a slight knee bend, hinge at the hips and lower the bar along your shins until you feel a stretch in your hamstrings, then drive your hips forward to stand.",
    ),
    dict(
        name="Hyperextension",
        muscle_group="back",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.5,
        is_compound=False,
        instructions="On a back extension bench with your hips supported, lower your torso forward, then raise it back up to a straight line without hyperextending your spine.",
    ),
    dict(
        name="Straight-Arm Pulldown",
        muscle_group="back",
        equipment="cable",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.5,
        is_compound=False,
        instructions="With arms straight and a slight forward lean, pull the bar down from overhead to your thighs using only your lats, then return under control.",
    ),
    dict(
        name="Machine Row",
        muscle_group="back",
        equipment="machine",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=60,
        calories_per_set=5.5,
        is_compound=True,
        instructions="Seated with your chest against the pad, pull both handles back, squeezing your shoulder blades together, then return under control.",
    ),
    dict(
        name="Renegade Row",
        muscle_group="back",
        equipment="dumbbells",
        difficulty="advanced",
        exercise_type="strength",
        default_sets=3,
        default_reps="8-10 per side",
        rest_seconds=75,
        calories_per_set=6.5,
        is_compound=True,
        instructions="In a plank position with hands on dumbbells, row one dumbbell up to your ribs while bracing your core to resist rotating, then switch sides.",
    ),
    # ------------------------------------------------------------ Shoulders
    dict(
        name="Barbell Overhead Press",
        muscle_group="shoulders",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=4,
        default_reps="6-8",
        rest_seconds=90,
        calories_per_set=7.5,
        is_compound=True,
        instructions="Standing with the bar at shoulder height, press it straight overhead until your arms are locked out, then lower back to your shoulders.",
    ),
    dict(
        name="Dumbbell Shoulder Press",
        muscle_group="shoulders",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=4,
        default_reps="8-12",
        rest_seconds=75,
        calories_per_set=6.5,
        is_compound=True,
        instructions="Seated or standing, press both dumbbells from shoulder height straight overhead, then lower with control.",
    ),
    dict(
        name="Arnold Press",
        muscle_group="shoulders",
        equipment="dumbbells",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="8-10",
        rest_seconds=75,
        calories_per_set=6.5,
        is_compound=True,
        instructions="Start with palms facing you at shoulder height, rotate your palms outward as you press overhead, then reverse the rotation on the way down.",
    ),
    dict(
        name="Lateral Raise",
        muscle_group="shoulders",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="With a slight bend in your elbows, raise both dumbbells out to your sides until level with your shoulders, then lower with control.",
    ),
    dict(
        name="Front Raise",
        muscle_group="shoulders",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Raise both dumbbells straight out in front of you to shoulder height, then lower under control without swinging.",
    ),
    dict(
        name="Rear Delt Fly",
        muscle_group="shoulders",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Hinged forward at the hips, raise both dumbbells out to the sides, squeezing your rear shoulders at the top, then lower slowly.",
    ),
    dict(
        name="Cable Lateral Raise",
        muscle_group="shoulders",
        equipment="cable",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Standing side-on to a low cable, raise the handle out and up to shoulder height, then lower under control.",
    ),
    dict(
        name="Upright Row",
        muscle_group="shoulders",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=60,
        calories_per_set=5.5,
        is_compound=True,
        instructions="Grip the bar shoulder-width, pull it straight up along your torso to chest height leading with your elbows, then lower with control.",
    ),
    dict(
        name="Machine Shoulder Press",
        muscle_group="shoulders",
        equipment="machine",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=75,
        calories_per_set=5.5,
        is_compound=True,
        instructions="Seated with your back supported, press both handles overhead until your arms are extended, then return under control.",
    ),
    dict(
        name="Barbell Shrug",
        muscle_group="shoulders",
        equipment="barbell",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=60,
        calories_per_set=4.5,
        is_compound=False,
        instructions="Holding the bar in front of your thighs, raise your shoulders straight up towards your ears, then lower with control — avoid rolling them.",
    ),
    dict(
        name="Dumbbell Shrug",
        muscle_group="shoulders",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=60,
        calories_per_set=4.5,
        is_compound=False,
        instructions="Holding a dumbbell in each hand at your sides, raise your shoulders straight up, hold briefly, then lower with control.",
    ),
    dict(
        name="Pike Push-Up",
        muscle_group="shoulders",
        equipment="bodyweight",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="8-12",
        rest_seconds=60,
        calories_per_set=5.5,
        is_compound=True,
        instructions="In a downward-dog position with hips raised, bend your elbows to lower your head towards the floor, then press back up.",
    ),
    dict(
        name="Reverse Pec Deck",
        muscle_group="shoulders",
        equipment="machine",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Facing the pad with arms extended in front of you, pull both handles back and out to the sides, squeezing your rear shoulders.",
    ),
    dict(
        name="Landmine Press",
        muscle_group="shoulders",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="8-10 per side",
        rest_seconds=75,
        calories_per_set=6.0,
        is_compound=True,
        instructions="With one end of the bar anchored, press the other end up and slightly forward from shoulder height until your arm is extended, then lower with control.",
    ),
    # ----------------------------------------------------------------- Legs
    dict(
        name="Barbell Back Squat",
        muscle_group="legs",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=4,
        default_reps="6-8",
        rest_seconds=120,
        calories_per_set=9.0,
        is_compound=True,
        instructions="Bar across your upper back, feet shoulder-width apart, sit your hips back and down until your thighs are at least parallel to the floor, then drive back up.",
    ),
    dict(
        name="Front Squat",
        muscle_group="legs",
        equipment="barbell",
        difficulty="advanced",
        exercise_type="strength",
        default_sets=4,
        default_reps="6-8",
        rest_seconds=120,
        calories_per_set=9.0,
        is_compound=True,
        instructions="Bar resting across the front of your shoulders, elbows high, squat down keeping your torso upright, then drive back up through your heels.",
    ),
    dict(
        name="Leg Press",
        muscle_group="legs",
        equipment="machine",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=4,
        default_reps="10-12",
        rest_seconds=90,
        calories_per_set=8.0,
        is_compound=True,
        instructions="Feet shoulder-width on the platform, lower the weight until your knees reach about 90 degrees, then press back up without locking your knees out hard.",
    ),
    dict(
        name="Walking Lunge",
        muscle_group="legs",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12 per leg",
        rest_seconds=75,
        calories_per_set=7.0,
        is_compound=True,
        instructions="Holding a dumbbell in each hand, step forward into a lunge until your back knee nearly touches the floor, then push off into the next step.",
    ),
    dict(
        name="Bulgarian Split Squat",
        muscle_group="legs",
        equipment="dumbbells",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12 per leg",
        rest_seconds=75,
        calories_per_set=7.0,
        is_compound=True,
        instructions="With your rear foot elevated on a bench behind you, lower your hips until your front thigh is parallel to the floor, then drive back up through your front heel.",
    ),
    dict(
        name="Leg Extension",
        muscle_group="legs",
        equipment="machine",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=60,
        calories_per_set=5.5,
        is_compound=False,
        instructions="Seated with the pad against your shins, extend your legs straight out, then lower back down under control.",
    ),
    dict(
        name="Lying Leg Curl",
        muscle_group="legs",
        equipment="machine",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=60,
        calories_per_set=5.5,
        is_compound=False,
        instructions="Lying face down with the pad against your heels, curl your legs up towards your glutes, then lower with control.",
    ),
    dict(
        name="Dumbbell Romanian Deadlift",
        muscle_group="legs",
        equipment="dumbbells",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=75,
        calories_per_set=6.5,
        is_compound=True,
        instructions="Holding a dumbbell in each hand, hinge at the hips and lower them along your shins until you feel a hamstring stretch, then stand back up.",
    ),
    dict(
        name="Barbell Hip Thrust",
        muscle_group="legs",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=4,
        default_reps="10-12",
        rest_seconds=90,
        calories_per_set=7.0,
        is_compound=True,
        instructions="Upper back braced against a bench with the bar over your hips, drive your hips up until your body forms a straight line, then lower with control.",
    ),
    dict(
        name="Glute Bridge",
        muscle_group="legs",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="15-20",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Lying on your back with knees bent, drive your hips up by squeezing your glutes until your body forms a straight line, then lower under control.",
    ),
    dict(
        name="Standing Calf Raise",
        muscle_group="legs",
        equipment="machine",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=4,
        default_reps="15-20",
        rest_seconds=45,
        calories_per_set=3.5,
        is_compound=False,
        instructions="Standing with the balls of your feet on the platform, rise up onto your toes as high as possible, then lower your heels below the platform for a full stretch.",
    ),
    dict(
        name="Seated Calf Raise",
        muscle_group="legs",
        equipment="machine",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=4,
        default_reps="15-20",
        rest_seconds=45,
        calories_per_set=3.5,
        is_compound=False,
        instructions="Seated with the pads on your knees and balls of your feet on the platform, raise your heels as high as possible, then lower for a full stretch.",
    ),
    dict(
        name="Goblet Squat",
        muscle_group="legs",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=60,
        calories_per_set=6.0,
        is_compound=True,
        instructions="Holding a dumbbell vertically against your chest, squat down between your knees keeping your torso upright, then drive back up.",
    ),
    dict(
        name="Dumbbell Step-Up",
        muscle_group="legs",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12 per leg",
        rest_seconds=60,
        calories_per_set=6.0,
        is_compound=True,
        instructions="Holding a dumbbell in each hand, step up onto a bench leading with one foot, drive through that heel to stand tall, then step back down with control.",
    ),
    dict(
        name="Box Jump",
        muscle_group="legs",
        equipment="bodyweight",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=4,
        default_reps="8-10",
        rest_seconds=90,
        calories_per_set=7.0,
        is_compound=True,
        instructions="Standing in front of a box, swing your arms and jump explosively onto the box, landing softly with bent knees, then step back down.",
    ),
    dict(
        name="Machine Hack Squat",
        muscle_group="legs",
        equipment="machine",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=4,
        default_reps="8-10",
        rest_seconds=90,
        calories_per_set=8.0,
        is_compound=True,
        instructions="Shoulders under the pads and feet shoulder-width on the platform, lower until your thighs are parallel to the platform, then press back up.",
    ),
    # ----------------------------------------------------------------- Arms
    dict(
        name="Barbell Bicep Curl",
        muscle_group="arms",
        equipment="barbell",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=60,
        calories_per_set=4.5,
        is_compound=False,
        instructions="Standing with an underhand, shoulder-width grip, curl the bar up towards your shoulders without swinging your elbows forward, then lower with control.",
    ),
    dict(
        name="Dumbbell Bicep Curl",
        muscle_group="arms",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=60,
        calories_per_set=4.0,
        is_compound=False,
        instructions="With a dumbbell in each hand at your sides, curl them up towards your shoulders, keeping your elbows pinned, then lower under control.",
    ),
    dict(
        name="Hammer Curl",
        muscle_group="arms",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=60,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Holding the dumbbells with a neutral, palms-facing-in grip, curl them up towards your shoulders, then lower with control.",
    ),
    dict(
        name="Cable Bicep Curl",
        muscle_group="arms",
        equipment="cable",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Standing in front of a low cable with a straight bar attachment, curl the bar up towards your shoulders, then lower under control.",
    ),
    dict(
        name="Concentration Curl",
        muscle_group="arms",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12 per side",
        rest_seconds=45,
        calories_per_set=3.5,
        is_compound=False,
        instructions="Seated, brace your elbow against the inside of your thigh and curl the dumbbell up towards your shoulder, then lower with control.",
    ),
    dict(
        name="Close-Grip Bench Press",
        muscle_group="arms",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=4,
        default_reps="8-10",
        rest_seconds=90,
        calories_per_set=7.0,
        is_compound=True,
        instructions="Grip the bar about shoulder-width apart, lower it to your lower chest keeping your elbows tucked in, then press back up to extend your triceps.",
    ),
    dict(
        name="Tricep Dip",
        muscle_group="arms",
        equipment="bodyweight",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-15",
        rest_seconds=60,
        calories_per_set=6.0,
        is_compound=True,
        instructions="Hands on a bench behind you with legs extended, lower your body by bending your elbows, then press back up to straighten your arms.",
    ),
    dict(
        name="Cable Tricep Pushdown",
        muscle_group="arms",
        equipment="cable",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="With elbows pinned to your sides, push the bar down until your arms are fully extended, then let it rise back under control.",
    ),
    dict(
        name="Dumbbell Overhead Tricep Extension",
        muscle_group="arms",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=60,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Holding one dumbbell with both hands overhead, lower it behind your head by bending your elbows, then extend back up.",
    ),
    dict(
        name="Barbell Skull Crusher",
        muscle_group="arms",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=60,
        calories_per_set=4.5,
        is_compound=False,
        instructions="Lying on a bench holding the bar above your chest, bend your elbows to lower it towards your forehead, then extend back up without moving your upper arms.",
    ),
    dict(
        name="Barbell Preacher Curl",
        muscle_group="arms",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=60,
        calories_per_set=4.5,
        is_compound=False,
        instructions="With your upper arms braced against the preacher pad, curl the bar up towards your shoulders, then lower it for a full stretch.",
    ),
    dict(
        name="Cable Overhead Tricep Extension",
        muscle_group="arms",
        equipment="cable",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Facing away from a low cable with the rope overhead, extend your arms forward and up until straight, then return under control.",
    ),
    dict(
        name="Barbell Reverse Curl",
        muscle_group="arms",
        equipment="barbell",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-12",
        rest_seconds=60,
        calories_per_set=4.0,
        is_compound=False,
        instructions="With an overhand grip, curl the bar up towards your shoulders, keeping your wrists firm, then lower with control.",
    ),
    dict(
        name="Dumbbell Wrist Curl",
        muscle_group="arms",
        equipment="dumbbells",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="15-20",
        rest_seconds=30,
        calories_per_set=2.5,
        is_compound=False,
        instructions="Forearms resting on your thighs with palms up, curl your wrists up to lift the dumbbells, then lower for a full stretch.",
    ),
    # ----------------------------------------------------------------- Core
    dict(
        name="Plank",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="30-60 sec",
        rest_seconds=45,
        calories_per_set=None,
        is_compound=True,
        instructions="Forearms on the floor and body in a straight line from head to heels, brace your core and hold the position without letting your hips sag.",
    ),
    dict(
        name="Side Plank",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="20-40 sec per side",
        rest_seconds=45,
        calories_per_set=None,
        is_compound=True,
        instructions="Propped up on one forearm with your body in a straight line, raise your hips and hold, keeping your top hip stacked over the bottom one.",
    ),
    dict(
        name="Crunch",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="15-20",
        rest_seconds=45,
        calories_per_set=3.0,
        is_compound=False,
        instructions="Lying on your back with knees bent, curl your shoulders up off the floor towards your knees, then lower with control.",
    ),
    dict(
        name="Bicycle Crunch",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="15-20 per side",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Lying on your back, bring one elbow towards the opposite knee while extending the other leg, then alternate sides in a pedaling motion.",
    ),
    dict(
        name="Russian Twist",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="20-30 total",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Seated with knees bent and feet slightly raised, lean back slightly and rotate your torso to tap the floor on each side.",
    ),
    dict(
        name="Hanging Leg Raise",
        muscle_group="core",
        equipment="pull_up_bar",
        difficulty="advanced",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-15",
        rest_seconds=60,
        calories_per_set=5.5,
        is_compound=True,
        instructions="Hanging from a pull-up bar with arms straight, raise your legs up towards your chest without swinging, then lower with control.",
    ),
    dict(
        name="Lying Leg Raise",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Lying on your back with legs straight, raise them up to vertical while keeping your lower back pressed into the floor, then lower with control.",
    ),
    dict(
        name="Mountain Climber",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="cardio",
        default_sets=3,
        default_reps="30-45 sec",
        rest_seconds=45,
        calories_per_set=6.0,
        is_compound=True,
        instructions="In a plank position, drive your knees alternately towards your chest at a quick pace while keeping your hips low and core braced.",
    ),
    dict(
        name="Cable Woodchopper",
        muscle_group="core",
        equipment="cable",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15 per side",
        rest_seconds=60,
        calories_per_set=5.0,
        is_compound=False,
        instructions="With the cable set high, rotate your torso to pull the handle down and across your body to the opposite hip, then return under control.",
    ),
    dict(
        name="Flutter Kicks",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="30-40 sec",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Lying on your back with legs straight and slightly raised, alternate small up-and-down kicks while keeping your lower back pressed into the floor.",
    ),
    dict(
        name="Sit-Up",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="strength",
        default_sets=3,
        default_reps="15-20",
        rest_seconds=45,
        calories_per_set=4.0,
        is_compound=False,
        instructions="Lying on your back with knees bent and feet anchored, curl your entire torso up until you're sitting upright, then lower with control.",
    ),
    dict(
        name="Dead Bug",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="mobility",
        default_sets=3,
        default_reps="10-12 per side",
        rest_seconds=45,
        calories_per_set=3.0,
        is_compound=False,
        instructions="Lying on your back with arms and legs raised, slowly extend one arm and the opposite leg towards the floor while keeping your lower back flat, then return and switch.",
    ),
    dict(
        name="Cable Crunch",
        muscle_group="core",
        equipment="cable",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="12-15",
        rest_seconds=45,
        calories_per_set=4.5,
        is_compound=False,
        instructions="Kneeling below a high cable with the rope behind your head, crunch your torso down towards your knees by flexing your abs, then return under control.",
    ),
    dict(
        name="V-Up",
        muscle_group="core",
        equipment="bodyweight",
        difficulty="intermediate",
        exercise_type="strength",
        default_sets=3,
        default_reps="10-15",
        rest_seconds=45,
        calories_per_set=4.5,
        is_compound=True,
        instructions="Lying flat, simultaneously raise your legs and torso to meet in a V-shape, reaching your hands towards your feet, then lower back down with control.",
    ),
    # --------------------------------------------------------------- Cardio
    dict(
        name="Treadmill Running",
        muscle_group="cardio",
        equipment="machine",
        difficulty="beginner",
        exercise_type="cardio",
        default_sets=1,
        default_reps="20 min",
        rest_seconds=0,
        calories_per_set=200.0,
        is_compound=True,
        instructions="Run at a steady, sustainable pace, keeping your posture upright and your stride relaxed for the full duration.",
    ),
    dict(
        name="Stationary Cycling",
        muscle_group="cardio",
        equipment="machine",
        difficulty="beginner",
        exercise_type="cardio",
        default_sets=1,
        default_reps="30 min",
        rest_seconds=0,
        calories_per_set=250.0,
        is_compound=True,
        instructions="Set a moderate resistance and pedal at a steady cadence, keeping a slight bend in your knee at full extension.",
    ),
    dict(
        name="Rowing Machine",
        muscle_group="cardio",
        equipment="machine",
        difficulty="intermediate",
        exercise_type="cardio",
        default_sets=1,
        default_reps="20 min",
        rest_seconds=0,
        calories_per_set=220.0,
        is_compound=True,
        instructions="Drive through your legs first, then lean back and pull the handle to your chest, reversing the sequence smoothly on the way forward.",
    ),
    dict(
        name="Jump Rope",
        muscle_group="cardio",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="cardio",
        default_sets=3,
        default_reps="2 min",
        rest_seconds=60,
        calories_per_set=25.0,
        is_compound=True,
        instructions="Keep your jumps small and your wrists doing most of the rope's work, landing softly on the balls of your feet.",
    ),
    dict(
        name="Burpees",
        muscle_group="cardio",
        equipment="bodyweight",
        difficulty="intermediate",
        exercise_type="cardio",
        default_sets=4,
        default_reps="45 sec",
        rest_seconds=60,
        calories_per_set=18.0,
        is_compound=True,
        instructions="Drop into a squat, kick your feet back into a plank, perform a push-up, jump your feet back in, then explode straight up into a jump.",
    ),
    dict(
        name="High Knees",
        muscle_group="cardio",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="cardio",
        default_sets=3,
        default_reps="30 sec",
        rest_seconds=45,
        calories_per_set=10.0,
        is_compound=True,
        instructions="Run in place, driving your knees up towards your chest as quickly as you can while pumping your arms.",
    ),
    dict(
        name="Jumping Jacks",
        muscle_group="cardio",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="cardio",
        default_sets=3,
        default_reps="1 min",
        rest_seconds=45,
        calories_per_set=12.0,
        is_compound=True,
        instructions="Jump your feet out wide while raising your arms overhead, then jump back to the start position in one fluid motion.",
    ),
    dict(
        name="Battle Ropes",
        muscle_group="cardio",
        equipment="machine",
        difficulty="intermediate",
        exercise_type="cardio",
        default_sets=5,
        default_reps="30 sec",
        rest_seconds=45,
        calories_per_set=15.0,
        is_compound=True,
        instructions="Holding one end of each rope, alternate slamming your arms up and down as fast as you can while keeping your knees soft.",
    ),
    dict(
        name="Stair Climber",
        muscle_group="cardio",
        equipment="machine",
        difficulty="beginner",
        exercise_type="cardio",
        default_sets=1,
        default_reps="15 min",
        rest_seconds=0,
        calories_per_set=180.0,
        is_compound=True,
        instructions="Step at a steady pace without leaning heavily on the rails, keeping your posture tall throughout.",
    ),
    dict(
        name="Sprint Intervals",
        muscle_group="cardio",
        equipment="bodyweight",
        difficulty="advanced",
        exercise_type="cardio",
        default_sets=8,
        default_reps="30 sec",
        rest_seconds=60,
        calories_per_set=20.0,
        is_compound=True,
        instructions="Sprint at maximum effort for the work interval, then walk or jog lightly during the rest interval to recover.",
    ),
    dict(
        name="Elliptical Trainer",
        muscle_group="cardio",
        equipment="machine",
        difficulty="beginner",
        exercise_type="cardio",
        default_sets=1,
        default_reps="25 min",
        rest_seconds=0,
        calories_per_set=210.0,
        is_compound=True,
        instructions="Maintain a smooth, steady stride while lightly gripping the moving handles, keeping your core engaged.",
    ),
    dict(
        name="Kettlebell Swing",
        muscle_group="cardio",
        equipment="kettlebell",
        difficulty="intermediate",
        exercise_type="cardio",
        default_sets=4,
        default_reps="15-20",
        rest_seconds=60,
        calories_per_set=12.0,
        is_compound=True,
        instructions="Hinge at the hips to swing the kettlebell back between your legs, then snap your hips forward to drive it up to chest height.",
    ),
    dict(
        name="Cardio Step-Ups",
        muscle_group="cardio",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="cardio",
        default_sets=3,
        default_reps="1 min",
        rest_seconds=45,
        calories_per_set=10.0,
        is_compound=True,
        instructions="Step quickly up and down onto a sturdy bench or box, alternating your lead foot at a brisk, sustained pace.",
    ),
    dict(
        name="Shadow Boxing",
        muscle_group="cardio",
        equipment="bodyweight",
        difficulty="beginner",
        exercise_type="cardio",
        default_sets=3,
        default_reps="2 min",
        rest_seconds=45,
        calories_per_set=15.0,
        is_compound=True,
        instructions="Throw continuous combinations of punches against an imaginary opponent, staying light on your feet and rotating your hips through each punch.",
    ),
]


def seed_exercises(db: Session) -> int:
    """Inserts the seed exercises if the library is empty.

    Returns the number of rows inserted (0 if the library was already
    seeded). Called from the app's startup lifespan (`app/main.py`) — safe to
    call on every boot since it's a no-op once seeded.
    """
    if exercise_repository.count(db) > 0:
        return 0

    validated_rows = [ExerciseCreate(**row).model_dump() for row in _EXERCISES]
    exercise_repository.bulk_create(db, rows=validated_rows)
    return len(validated_rows)
