"""initial_schema

Revision ID: ca10796a2c38
Revises:
Create Date: 2026-07-01 11:57:57.003476

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca10796a2c38"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "muscle_group",
            sa.Enum(
                "chest",
                "back",
                "shoulders",
                "legs",
                "arms",
                "core",
                "cardio",
                name="musclegroup",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "equipment",
            sa.Enum(
                "bodyweight",
                "dumbbells",
                "barbell",
                "kettlebell",
                "resistance_bands",
                "machine",
                "cable",
                "bench",
                "pull_up_bar",
                name="exerciseequipment",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum("beginner", "intermediate", "advanced", name="difficulty", native_enum=False),
            nullable=False,
        ),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column(
            "exercise_type",
            sa.Enum(
                "strength", "cardio", "mobility", "balance", name="exercisetype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("default_sets", sa.Integer(), nullable=False),
        sa.Column("default_reps", sa.String(length=20), nullable=False),
        sa.Column("rest_seconds", sa.Integer(), nullable=False),
        sa.Column("calories_per_set", sa.Float(), nullable=True),
        sa.Column("is_compound", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exercises_difficulty"), ["difficulty"], unique=False)
        batch_op.create_index(batch_op.f("ix_exercises_equipment"), ["equipment"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_exercises_muscle_group"), ["muscle_group"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_exercises_name"), ["name"], unique=False)

    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "body_measurements",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("log_date", sa.String(length=10), nullable=False),
        sa.Column("chest_cm", sa.Float(), nullable=True),
        sa.Column("waist_cm", sa.Float(), nullable=True),
        sa.Column("hips_cm", sa.Float(), nullable=True),
        sa.Column("left_arm_cm", sa.Float(), nullable=True),
        sa.Column("right_arm_cm", sa.Float(), nullable=True),
        sa.Column("left_thigh_cm", sa.Float(), nullable=True),
        sa.Column("right_thigh_cm", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("body_measurements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_body_measurements_log_date"), ["log_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_body_measurements_user_id"), ["user_id"], unique=False)

    op.create_table(
        "nutrition_logs",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("log_date", sa.String(length=10), nullable=False),
        sa.Column("calories_consumed", sa.Integer(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("carbs_g", sa.Float(), nullable=False),
        sa.Column("fat_g", sa.Float(), nullable=False),
        sa.Column("water_ml", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("nutrition_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nutrition_logs_log_date"), ["log_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_nutrition_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "nutrition_plans",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "diet_type",
            sa.Enum(
                "vegetarian", "non_vegetarian", "vegan", name="dietpreference", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("target_calories", sa.Integer(), nullable=False),
        sa.Column("target_protein_g", sa.Float(), nullable=False),
        sa.Column("target_carbs_g", sa.Float(), nullable=False),
        sa.Column("target_fat_g", sa.Float(), nullable=False),
        sa.Column("target_water_ml", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("nutrition_plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nutrition_plans_user_id"), ["user_id"], unique=False)

    op.create_table(
        "profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("male", "female", "other", name="gender", native_enum=False),
            nullable=False,
        ),
        sa.Column("height_cm", sa.Float(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column(
            "fitness_goal",
            sa.Enum(
                "weight_loss",
                "muscle_gain",
                "maintenance",
                "general_fitness",
                name="fitnessgoal",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "activity_level",
            sa.Enum(
                "sedentary",
                "lightly_active",
                "moderately_active",
                "very_active",
                "extra_active",
                name="activitylevel",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "workout_experience",
            sa.Enum(
                "beginner", "intermediate", "advanced", name="workoutexperience", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("equipment_available", sa.JSON(), nullable=False),
        sa.Column(
            "diet_preference",
            sa.Enum(
                "vegetarian", "non_vegetarian", "vegan", name="dietpreference", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "progress_logs",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("log_date", sa.String(length=10), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("body_fat_pct", sa.Float(), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("progress_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_progress_logs_log_date"), ["log_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_progress_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "workout_plans",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column(
            "goal",
            sa.Enum(
                "weight_loss",
                "muscle_gain",
                "maintenance",
                "general_fitness",
                name="fitnessgoal",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "experience",
            sa.Enum(
                "beginner", "intermediate", "advanced", name="workoutexperience", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("workout_days", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workout_plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workout_plans_user_id"), ["user_id"], unique=False)

    op.create_table(
        "meals",
        sa.Column("nutrition_plan_id", sa.String(length=36), nullable=False),
        sa.Column(
            "meal_type",
            sa.Enum("breakfast", "lunch", "dinner", "snack", name="mealtype", native_enum=False),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("carbs_g", sa.Float(), nullable=False),
        sa.Column("fat_g", sa.Float(), nullable=False),
        sa.Column("fiber_g", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["nutrition_plan_id"], ["nutrition_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("meals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_meals_nutrition_plan_id"), ["nutrition_plan_id"], unique=False
        )

    op.create_table(
        "workout_days",
        sa.Column("workout_plan_id", sa.String(length=36), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("day_name", sa.String(length=100), nullable=False),
        sa.Column("focus_area", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workout_plan_id"], ["workout_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workout_days", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workout_days_workout_plan_id"), ["workout_plan_id"], unique=False
        )

    op.create_table(
        "workout_exercises",
        sa.Column("workout_day_id", sa.String(length=36), nullable=False),
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=False),
        sa.Column("reps", sa.String(length=20), nullable=False),
        sa.Column("rest_seconds", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(["workout_day_id"], ["workout_days.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workout_exercises", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workout_exercises_exercise_id"), ["exercise_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workout_exercises_workout_day_id"), ["workout_day_id"], unique=False
        )

    op.create_table(
        "workout_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("workout_plan_id", sa.String(length=36), nullable=False),
        sa.Column("workout_day_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "paused", "completed", name="workoutsessionstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("calories_burned_estimate", sa.Float(), nullable=True),
        sa.Column("accumulated_active_seconds", sa.Integer(), nullable=False),
        sa.Column("last_resumed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workout_day_id"], ["workout_days.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workout_plan_id"], ["workout_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workout_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workout_sessions_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_workout_sessions_workout_day_id"), ["workout_day_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workout_sessions_workout_plan_id"), ["workout_plan_id"], unique=False
        )

    op.create_table(
        "exercise_completions",
        sa.Column("workout_session_id", sa.String(length=36), nullable=False),
        sa.Column("workout_exercise_id", sa.String(length=36), nullable=False),
        sa.Column("completed_sets", sa.Integer(), nullable=False),
        sa.Column("completed_reps", sa.String(length=20), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workout_exercise_id"],
            ["workout_exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_session_id"], ["workout_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("exercise_completions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exercise_completions_workout_exercise_id"),
            ["workout_exercise_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_exercise_completions_workout_session_id"),
            ["workout_session_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exercise_completions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exercise_completions_workout_session_id"))
        batch_op.drop_index(batch_op.f("ix_exercise_completions_workout_exercise_id"))

    op.drop_table("exercise_completions")
    with op.batch_alter_table("workout_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workout_sessions_workout_plan_id"))
        batch_op.drop_index(batch_op.f("ix_workout_sessions_workout_day_id"))
        batch_op.drop_index(batch_op.f("ix_workout_sessions_user_id"))

    op.drop_table("workout_sessions")
    with op.batch_alter_table("workout_exercises", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workout_exercises_workout_day_id"))
        batch_op.drop_index(batch_op.f("ix_workout_exercises_exercise_id"))

    op.drop_table("workout_exercises")
    with op.batch_alter_table("workout_days", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workout_days_workout_plan_id"))

    op.drop_table("workout_days")
    with op.batch_alter_table("meals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_meals_nutrition_plan_id"))

    op.drop_table("meals")
    with op.batch_alter_table("workout_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workout_plans_user_id"))

    op.drop_table("workout_plans")
    with op.batch_alter_table("progress_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_progress_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_progress_logs_log_date"))

    op.drop_table("progress_logs")
    op.drop_table("profiles")
    with op.batch_alter_table("nutrition_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nutrition_plans_user_id"))

    op.drop_table("nutrition_plans")
    with op.batch_alter_table("nutrition_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nutrition_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_nutrition_logs_log_date"))

    op.drop_table("nutrition_logs")
    with op.batch_alter_table("body_measurements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_body_measurements_user_id"))
        batch_op.drop_index(batch_op.f("ix_body_measurements_log_date"))

    op.drop_table("body_measurements")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exercises_name"))
        batch_op.drop_index(batch_op.f("ix_exercises_muscle_group"))
        batch_op.drop_index(batch_op.f("ix_exercises_equipment"))
        batch_op.drop_index(batch_op.f("ix_exercises_difficulty"))

    op.drop_table("exercises")
    # ### end Alembic commands ###
