"use client";

import { motion, type Variants } from "framer-motion";
import { Bot, Shield, Sparkles } from "lucide-react";
import { useState } from "react";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { GlassCard } from "@/components/shared/glass-card";
import { cn } from "@/lib/utils";
import type { GeneratedWorkoutPlanResponse } from "@/types/user";

type ConfidenceTier = "excellent" | "high" | "moderate" | "low";

function getConfidenceTier(confidence: number): ConfidenceTier {
  const pct = confidence * 100;
  if (pct >= 95) return "excellent";
  if (pct >= 85) return "high";
  if (pct >= 70) return "moderate";
  return "low";
}

const TIER_LABEL: Record<ConfidenceTier, string> = {
  excellent: "Excellent",
  high: "High",
  moderate: "Moderate",
  low: "Low",
};

// Maps each confidence tier to a Badge variant already defined in the
// design system (success/warning/destructive) — no new colors introduced.
const TIER_BADGE_VARIANT: Record<ConfidenceTier, "success" | "default" | "warning" | "destructive"> = {
  excellent: "success",
  high: "default",
  moderate: "warning",
  low: "destructive",
};

const TIER_BAR_CLASS: Record<ConfidenceTier, string> = {
  excellent: "bg-success",
  high: "bg-primary",
  moderate: "bg-warning",
  low: "bg-destructive",
};

const cardVariants: Variants = {
  hidden: { opacity: 0, y: 16, scale: 0.98 },
  visible: {
    opacity: 1,
    y: 0,
    scale: 1,
    transition: { duration: 0.5, ease: [0.16, 1, 0.3, 1] },
  },
};

const chipContainer: Variants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.05, delayChildren: 0.2 } },
};
const chipItem: Variants = {
  hidden: { opacity: 0, y: 8 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.3 } },
};

/**
 * The premium "AI Recommendation" reveal — shown right after a plan is
 * generated (driven by `useGenerateWorkout()`'s own mutation result, not a
 * persisted/re-fetched value — see app/(app)/workouts/page.tsx). Every
 * field it displays comes directly from the backend's
 * `GeneratedWorkoutPlanResponse` (engine/confidence/latency_ms/
 * model_version/explanation — see docs/ML_INTEGRATION.md and
 * backend/app/schemas/recommendation.py), nothing here is hardcoded or
 * guessed client-side.
 */
export function AIRecommendationCard({ plan }: { plan: GeneratedWorkoutPlanResponse }) {
  const [whyOpen, setWhyOpen] = useState<string | undefined>(undefined);
  const isMl = plan.engine === "ml";
  const tier = plan.confidence !== null ? getConfidenceTier(plan.confidence) : null;
  // Debug/dev-only Model Information footer — Next.js sets NODE_ENV
  // automatically at build time (production builds never expose it),
  // no extra env var needed.
  const showModelInfo = process.env.NODE_ENV !== "production";

  const chips: Array<{ label: string }> = plan.explanation
    ? [
        { label: plan.explanation.goal },
        { label: plan.explanation.experience },
        { label: `${plan.explanation.days_per_week} Days` },
        { label: plan.explanation.equipment },
        { label: plan.explanation.gender },
        { label: `Age ${plan.explanation.age}` },
      ]
    : [];

  return (
    <motion.div
      variants={cardVariants}
      initial="hidden"
      animate="visible"
      whileHover={{ y: -2 }}
      transition={{ type: "spring", stiffness: 300, damping: 25 }}
    >
      <GlassCard className="overflow-hidden p-6">
        {/* Header */}
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <Sparkles className="size-5 text-primary" aria-hidden />
            <span className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
              AI Recommendation
            </span>
          </div>

          {/* Recommendation source */}
          <Badge variant={isMl ? "default" : "outline"} className="gap-1.5">
            {isMl ? (
              <>
                <Bot className="size-3.5" aria-hidden />
                Generated by Machine Learning
              </>
            ) : (
              <>
                <Shield className="size-3.5" aria-hidden />
                Generated by Rule Engine (Fallback)
              </>
            )}
          </Badge>
        </div>

        {/* Recommended split */}
        <h3 className="mt-4 text-2xl font-bold tracking-tight sm:text-3xl">{plan.split_name}</h3>

        {/* Confidence — only rendered when the engine actually reports one
            (never shown/fabricated for the rule engine, per spec). */}
        {tier && plan.confidence !== null && (
          <div className="mt-5 space-y-2">
            <div className="flex items-center justify-between text-sm">
              <span className="text-muted-foreground">Confidence</span>
              <div className="flex items-center gap-2">
                <span className="font-semibold">{Math.round(plan.confidence * 100)}%</span>
                <Badge variant={TIER_BADGE_VARIANT[tier]} className="text-xs">
                  {TIER_LABEL[tier]}
                </Badge>
              </div>
            </div>
            <motion.div
              initial={{ scaleX: 0 }}
              animate={{ scaleX: 1 }}
              transition={{ duration: 0.8, delay: 0.3, ease: [0.16, 1, 0.3, 1] }}
              style={{ transformOrigin: "left" }}
            >
              <Progress
                value={plan.confidence * 100}
                indicatorClassName={cn(TIER_BAR_CLASS[tier])}
              />
            </motion.div>
          </div>
        )}

        {/* Why this plan? — collapsible */}
        {plan.explanation && (
          <Accordion
            type="single"
            collapsible
            value={whyOpen}
            onValueChange={setWhyOpen}
            className="mt-5"
          >
            <AccordionItem value="why" className="border-t">
              <AccordionTrigger className="text-sm font-medium hover:no-underline">
                Why was this recommended?
              </AccordionTrigger>
              <AccordionContent>
                <ul className="mb-3 space-y-1.5 text-sm text-muted-foreground">
                  <li>
                    <span className="text-foreground">Goal:</span> {plan.explanation.goal}
                  </li>
                  <li>
                    <span className="text-foreground">Experience:</span>{" "}
                    {plan.explanation.experience}
                  </li>
                  <li>
                    <span className="text-foreground">Training Days:</span>{" "}
                    {plan.explanation.days_per_week}/week
                  </li>
                  <li>
                    <span className="text-foreground">Equipment:</span>{" "}
                    {plan.explanation.equipment}
                  </li>
                </ul>
                <p className="text-sm text-muted-foreground">
                  This recommendation is based on your fitness profile, training frequency,
                  available equipment, and historical patterns learned by our recommendation
                  model.
                </p>
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        )}

        {/* Prediction detail chips */}
        {chips.length > 0 && (
          <motion.div
            variants={chipContainer}
            initial="hidden"
            animate="visible"
            className="mt-5 flex flex-wrap gap-2"
          >
            {chips.map((chip) => (
              <motion.div key={chip.label} variants={chipItem}>
                <Badge variant="secondary" className="font-normal">
                  {chip.label}
                </Badge>
              </motion.div>
            ))}
          </motion.div>
        )}

        {/* Model information — development/debug only */}
        {showModelInfo && (
          <div className="mt-5 flex flex-wrap gap-x-6 gap-y-1 border-t pt-4 text-xs text-muted-foreground">
            <span>
              Model Version <span className="font-medium text-foreground">{plan.model_version ?? "—"}</span>
            </span>
            <span>
              Engine{" "}
              <span className="font-medium text-foreground">
                {isMl ? "Random Forest Classifier" : "Rule Engine"}
              </span>
            </span>
            <span>
              Inference Time{" "}
              <span className="font-medium text-foreground">
                {plan.latency_ms !== null ? `${Math.round(plan.latency_ms)} ms` : "—"}
              </span>
            </span>
          </div>
        )}
      </GlassCard>
    </motion.div>
  );
}
